name: Send live server to Telegram

on:
  push:
    paths:
      - 'live.txt'

jobs:
  sender:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ=Asia/Tehran date +'%s')"

      - name: change file name
        run: |
          mv live.txt 'LIVE@${{ steps.date.outputs.date }}.txt'

      - name: Send File to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: " "
          document: ${{ github.workspace }}/LIVE@${{ steps.date.outputs.date }}.txt

