name: Send File to Telegram

on:
  push:
    paths:
      - 'live.txt'

jobs:
  sender:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Send File to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ -1001877329643 }}
          token: ${{ 5539774340:AAFB9uIm7-cEP42sKSNR6MSJN5jNBh1--tQ }}
          document: ${{ github.workspace }}/live.txt
