name: Send File to Telegram

on:
  push:
    paths:
      - 'live.txt'

jobs:
  sender:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Send File to Telegram
        uses: ./
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: ${{ github.workspace }}/live.txt
